on:
  push:
    branches:
    - master
jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Run Job
        run: ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }} node update_list
