on:
  push:
    branches:
    - main
    - release/*
jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
      - name: Install Dependencies
        run: npm install
      - name: Run Job
        run: ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }} node update_list
